version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      k8s.io:
        patterns:
          - "k8s.io/*"
      go.etcd.io:
        patterns:
          - "go.etcd.io/etcd/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
