version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "5:46"
    groups:
      k8s.io:
        patterns:
          - "k8s.io/*"
      go.etcd.io:
        patterns:
          - "go.etcd.io/etcd/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      time: "5:46"
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "v1.11.3"
    schedule:
      time: "5:46"
      interval: "daily"
    groups:
      k8s.io:
        patterns:
          - "k8s.io/*"
      go.etcd.io:
        patterns:
          - "go.etcd.io/etcd/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "v1.11.3"
    schedule:
      time: "5:46"
      interval: "daily"
